/*
 * This file is generated by jOOQ.
 */
package adapters.repository.jooq.tables.records;


import adapters.repository.jooq.tables.Balance;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BalanceRecord extends UpdatableRecordImpl<BalanceRecord> implements Record8<Integer, String, Long, Long, Timestamp, Timestamp, Integer, Date> {

    private static final long serialVersionUID = 410522878;

    /**
     * Setter for <code>remey.balance.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>remey.balance.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>remey.balance.users_id</code>.
     */
    public void setUsersId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>remey.balance.users_id</code>.
     */
    public String getUsersId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>remey.balance.income</code>.
     */
    public void setIncome(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>remey.balance.income</code>.
     */
    public Long getIncome() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>remey.balance.spending</code>.
     */
    public void setSpending(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>remey.balance.spending</code>.
     */
    public Long getSpending() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>remey.balance.create_at</code>.
     */
    public void setCreateAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>remey.balance.create_at</code>.
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>remey.balance.update_at</code>.
     */
    public void setUpdateAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>remey.balance.update_at</code>.
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>remey.balance.version</code>.
     */
    public void setVersion(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>remey.balance.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>remey.balance.balance_date</code>.
     */
    public void setBalanceDate(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>remey.balance.balance_date</code>.
     */
    public Date getBalanceDate() {
        return (Date) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Long, Long, Timestamp, Timestamp, Integer, Date> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Long, Long, Timestamp, Timestamp, Integer, Date> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Balance.BALANCE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Balance.BALANCE.USERS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Balance.BALANCE.INCOME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Balance.BALANCE.SPENDING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Balance.BALANCE.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Balance.BALANCE.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Balance.BALANCE.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field8() {
        return Balance.BALANCE.BALANCE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUsersId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getIncome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getSpending();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component8() {
        return getBalanceDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUsersId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getIncome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getSpending();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value8() {
        return getBalanceDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceRecord value2(String value) {
        setUsersId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceRecord value3(Long value) {
        setIncome(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceRecord value4(Long value) {
        setSpending(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceRecord value5(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceRecord value6(Timestamp value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceRecord value7(Integer value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceRecord value8(Date value) {
        setBalanceDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceRecord values(Integer value1, String value2, Long value3, Long value4, Timestamp value5, Timestamp value6, Integer value7, Date value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BalanceRecord
     */
    public BalanceRecord() {
        super(Balance.BALANCE);
    }

    /**
     * Create a detached, initialised BalanceRecord
     */
    public BalanceRecord(Integer id, String usersId, Long income, Long spending, Timestamp createAt, Timestamp updateAt, Integer version, Date balanceDate) {
        super(Balance.BALANCE);

        set(0, id);
        set(1, usersId);
        set(2, income);
        set(3, spending);
        set(4, createAt);
        set(5, updateAt);
        set(6, version);
        set(7, balanceDate);
    }
}
