/*
 * This file is generated by jOOQ.
 */
package adapters.repository.jooq.tables.records;


import adapters.repository.jooq.tables.TagsMap;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagsMapRecord extends UpdatableRecordImpl<TagsMapRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -1217563533;

    /**
     * Setter for <code>remey.tags_map.balance_id</code>.
     */
    public void setBalanceId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>remey.tags_map.balance_id</code>.
     */
    public Integer getBalanceId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>remey.tags_map.tags_id</code>.
     */
    public void setTagsId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>remey.tags_map.tags_id</code>.
     */
    public Integer getTagsId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TagsMap.TAGS_MAP.BALANCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TagsMap.TAGS_MAP.TAGS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getBalanceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getTagsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getBalanceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTagsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagsMapRecord value1(Integer value) {
        setBalanceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagsMapRecord value2(Integer value) {
        setTagsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagsMapRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TagsMapRecord
     */
    public TagsMapRecord() {
        super(TagsMap.TAGS_MAP);
    }

    /**
     * Create a detached, initialised TagsMapRecord
     */
    public TagsMapRecord(Integer balanceId, Integer tagsId) {
        super(TagsMap.TAGS_MAP);

        set(0, balanceId);
        set(1, tagsId);
    }
}
