/*
 * This file is generated by jOOQ.
 */
package adapters.repository.jooq.tables.records;


import adapters.repository.jooq.tables.UserSettings;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSettingsRecord extends UpdatableRecordImpl<UserSettingsRecord> implements Record3<Integer, Long, Timestamp> {

    private static final long serialVersionUID = 1562803067;

    /**
     * Setter for <code>remey.user_settings.users_id</code>.
     */
    public void setUsersId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>remey.user_settings.users_id</code>.
     */
    public Integer getUsersId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>remey.user_settings.init_savings</code>.
     */
    public void setInitSavings(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>remey.user_settings.init_savings</code>.
     */
    public Long getInitSavings() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>remey.user_settings.update_at</code>.
     */
    public void setUpdateAt(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>remey.user_settings.update_at</code>.
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Long, Timestamp> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Long, Timestamp> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserSettings.USER_SETTINGS.USERS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return UserSettings.USER_SETTINGS.INIT_SAVINGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return UserSettings.USER_SETTINGS.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getUsersId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getInitSavings();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUsersId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getInitSavings();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingsRecord value1(Integer value) {
        setUsersId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingsRecord value2(Long value) {
        setInitSavings(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingsRecord value3(Timestamp value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingsRecord values(Integer value1, Long value2, Timestamp value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserSettingsRecord
     */
    public UserSettingsRecord() {
        super(UserSettings.USER_SETTINGS);
    }

    /**
     * Create a detached, initialised UserSettingsRecord
     */
    public UserSettingsRecord(Integer usersId, Long initSavings, Timestamp updateAt) {
        super(UserSettings.USER_SETTINGS);

        set(0, usersId);
        set(1, initSavings);
        set(2, updateAt);
    }
}
