/*
 * This file is generated by jOOQ.
 */
package adapters.repository.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Balance implements Serializable {

    private static final long serialVersionUID = -921505025;

    private Integer   id;
    private String    usersId;
    private Long      income;
    private Long      spending;
    private Timestamp createAt;
    private Timestamp updateAt;
    private Integer   version;
    private Date      balanceDate;

    public Balance() {}

    public Balance(Balance value) {
        this.id = value.id;
        this.usersId = value.usersId;
        this.income = value.income;
        this.spending = value.spending;
        this.createAt = value.createAt;
        this.updateAt = value.updateAt;
        this.version = value.version;
        this.balanceDate = value.balanceDate;
    }

    public Balance(
        Integer   id,
        String    usersId,
        Long      income,
        Long      spending,
        Timestamp createAt,
        Timestamp updateAt,
        Integer   version,
        Date      balanceDate
    ) {
        this.id = id;
        this.usersId = usersId;
        this.income = income;
        this.spending = spending;
        this.createAt = createAt;
        this.updateAt = updateAt;
        this.version = version;
        this.balanceDate = balanceDate;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsersId() {
        return this.usersId;
    }

    public void setUsersId(String usersId) {
        this.usersId = usersId;
    }

    public Long getIncome() {
        return this.income;
    }

    public void setIncome(Long income) {
        this.income = income;
    }

    public Long getSpending() {
        return this.spending;
    }

    public void setSpending(Long spending) {
        this.spending = spending;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public void setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public void setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Date getBalanceDate() {
        return this.balanceDate;
    }

    public void setBalanceDate(Date balanceDate) {
        this.balanceDate = balanceDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Balance (");

        sb.append(id);
        sb.append(", ").append(usersId);
        sb.append(", ").append(income);
        sb.append(", ").append(spending);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(version);
        sb.append(", ").append(balanceDate);

        sb.append(")");
        return sb.toString();
    }
}
