/*
 * This file is generated by jOOQ.
 */
package adapters.repository.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagsMap implements Serializable {

    private static final long serialVersionUID = 605565852;

    private Integer balanceId;
    private Integer tagsId;

    public TagsMap() {}

    public TagsMap(TagsMap value) {
        this.balanceId = value.balanceId;
        this.tagsId = value.tagsId;
    }

    public TagsMap(
        Integer balanceId,
        Integer tagsId
    ) {
        this.balanceId = balanceId;
        this.tagsId = tagsId;
    }

    public Integer getBalanceId() {
        return this.balanceId;
    }

    public void setBalanceId(Integer balanceId) {
        this.balanceId = balanceId;
    }

    public Integer getTagsId() {
        return this.tagsId;
    }

    public void setTagsId(Integer tagsId) {
        this.tagsId = tagsId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TagsMap (");

        sb.append(balanceId);
        sb.append(", ").append(tagsId);

        sb.append(")");
        return sb.toString();
    }
}
