/*
 * This file is generated by jOOQ.
 */
package adapters.repository.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSettings implements Serializable {

    private static final long serialVersionUID = -1120943417;

    private String    usersId;
    private Long      initSavings;
    private Timestamp updateAt;

    public UserSettings() {}

    public UserSettings(UserSettings value) {
        this.usersId = value.usersId;
        this.initSavings = value.initSavings;
        this.updateAt = value.updateAt;
    }

    public UserSettings(
        String    usersId,
        Long      initSavings,
        Timestamp updateAt
    ) {
        this.usersId = usersId;
        this.initSavings = initSavings;
        this.updateAt = updateAt;
    }

    public String getUsersId() {
        return this.usersId;
    }

    public void setUsersId(String usersId) {
        this.usersId = usersId;
    }

    public Long getInitSavings() {
        return this.initSavings;
    }

    public void setInitSavings(Long initSavings) {
        this.initSavings = initSavings;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public void setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserSettings (");

        sb.append(usersId);
        sb.append(", ").append(initSavings);
        sb.append(", ").append(updateAt);

        sb.append(")");
        return sb.toString();
    }
}
