/*
 * This file is generated by jOOQ.
 */
package adapters.repository.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 207429347;

    private Integer   id;
    private String    mailAddress;
    private String    password;
    private Timestamp createAt;
    private Timestamp updateAt;

    public Users() {}

    public Users(Users value) {
        this.id = value.id;
        this.mailAddress = value.mailAddress;
        this.password = value.password;
        this.createAt = value.createAt;
        this.updateAt = value.updateAt;
    }

    public Users(
        Integer   id,
        String    mailAddress,
        String    password,
        Timestamp createAt,
        Timestamp updateAt
    ) {
        this.id = id;
        this.mailAddress = mailAddress;
        this.password = password;
        this.createAt = createAt;
        this.updateAt = updateAt;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getMailAddress() {
        return this.mailAddress;
    }

    public void setMailAddress(String mailAddress) {
        this.mailAddress = mailAddress;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public void setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public void setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(mailAddress);
        sb.append(", ").append(password);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateAt);

        sb.append(")");
        return sb.toString();
    }
}
