/*
 * This file is generated by jOOQ.
 */
package adapters.repository.jooq.tables.daos;


import adapters.repository.jooq.tables.Balance;
import adapters.repository.jooq.tables.records.BalanceRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BalanceDao extends DAOImpl<BalanceRecord, adapters.repository.jooq.tables.pojos.Balance, Integer> {

    /**
     * Create a new BalanceDao without any configuration
     */
    public BalanceDao() {
        super(Balance.BALANCE, adapters.repository.jooq.tables.pojos.Balance.class);
    }

    /**
     * Create a new BalanceDao with an attached configuration
     */
    public BalanceDao(Configuration configuration) {
        super(Balance.BALANCE, adapters.repository.jooq.tables.pojos.Balance.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(adapters.repository.jooq.tables.pojos.Balance object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<adapters.repository.jooq.tables.pojos.Balance> fetchById(Integer... values) {
        return fetch(Balance.BALANCE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public adapters.repository.jooq.tables.pojos.Balance fetchOneById(Integer value) {
        return fetchOne(Balance.BALANCE.ID, value);
    }

    /**
     * Fetch records that have <code>users_id IN (values)</code>
     */
    public List<adapters.repository.jooq.tables.pojos.Balance> fetchByUsersId(String... values) {
        return fetch(Balance.BALANCE.USERS_ID, values);
    }

    /**
     * Fetch records that have <code>income IN (values)</code>
     */
    public List<adapters.repository.jooq.tables.pojos.Balance> fetchByIncome(Long... values) {
        return fetch(Balance.BALANCE.INCOME, values);
    }

    /**
     * Fetch records that have <code>spending IN (values)</code>
     */
    public List<adapters.repository.jooq.tables.pojos.Balance> fetchBySpending(Long... values) {
        return fetch(Balance.BALANCE.SPENDING, values);
    }

    /**
     * Fetch records that have <code>create_at IN (values)</code>
     */
    public List<adapters.repository.jooq.tables.pojos.Balance> fetchByCreateAt(Timestamp... values) {
        return fetch(Balance.BALANCE.CREATE_AT, values);
    }

    /**
     * Fetch records that have <code>update_at IN (values)</code>
     */
    public List<adapters.repository.jooq.tables.pojos.Balance> fetchByUpdateAt(Timestamp... values) {
        return fetch(Balance.BALANCE.UPDATE_AT, values);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<adapters.repository.jooq.tables.pojos.Balance> fetchByVersion(Integer... values) {
        return fetch(Balance.BALANCE.VERSION, values);
    }

    /**
     * Fetch records that have <code>balance_date IN (values)</code>
     */
    public List<adapters.repository.jooq.tables.pojos.Balance> fetchByBalanceDate(Date... values) {
        return fetch(Balance.BALANCE.BALANCE_DATE, values);
    }
}
