/*
 * This file is generated by jOOQ.
 */
package adapters.repository.jooq.tables.daos;


import adapters.repository.jooq.tables.TagsMap;
import adapters.repository.jooq.tables.records.TagsMapRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagsMapDao extends DAOImpl<TagsMapRecord, adapters.repository.jooq.tables.pojos.TagsMap, Record2<Integer, Integer>> {

    /**
     * Create a new TagsMapDao without any configuration
     */
    public TagsMapDao() {
        super(TagsMap.TAGS_MAP, adapters.repository.jooq.tables.pojos.TagsMap.class);
    }

    /**
     * Create a new TagsMapDao with an attached configuration
     */
    public TagsMapDao(Configuration configuration) {
        super(TagsMap.TAGS_MAP, adapters.repository.jooq.tables.pojos.TagsMap.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Integer, Integer> getId(adapters.repository.jooq.tables.pojos.TagsMap object) {
        return compositeKeyRecord(object.getBalanceId(), object.getTagsId());
    }

    /**
     * Fetch records that have <code>balance_id IN (values)</code>
     */
    public List<adapters.repository.jooq.tables.pojos.TagsMap> fetchByBalanceId(Integer... values) {
        return fetch(TagsMap.TAGS_MAP.BALANCE_ID, values);
    }

    /**
     * Fetch records that have <code>tags_id IN (values)</code>
     */
    public List<adapters.repository.jooq.tables.pojos.TagsMap> fetchByTagsId(Integer... values) {
        return fetch(TagsMap.TAGS_MAP.TAGS_ID, values);
    }
}
