/*
 * This file is generated by jOOQ.
 */
package adapters.repository.jooq.tables.daos;


import adapters.repository.jooq.tables.Users;
import adapters.repository.jooq.tables.records.UsersRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersDao extends DAOImpl<UsersRecord, adapters.repository.jooq.tables.pojos.Users, Integer> {

    /**
     * Create a new UsersDao without any configuration
     */
    public UsersDao() {
        super(Users.USERS, adapters.repository.jooq.tables.pojos.Users.class);
    }

    /**
     * Create a new UsersDao with an attached configuration
     */
    public UsersDao(Configuration configuration) {
        super(Users.USERS, adapters.repository.jooq.tables.pojos.Users.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(adapters.repository.jooq.tables.pojos.Users object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<adapters.repository.jooq.tables.pojos.Users> fetchById(Integer... values) {
        return fetch(Users.USERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public adapters.repository.jooq.tables.pojos.Users fetchOneById(Integer value) {
        return fetchOne(Users.USERS.ID, value);
    }

    /**
     * Fetch records that have <code>mail_address IN (values)</code>
     */
    public List<adapters.repository.jooq.tables.pojos.Users> fetchByMailAddress(String... values) {
        return fetch(Users.USERS.MAIL_ADDRESS, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<adapters.repository.jooq.tables.pojos.Users> fetchByPassword(String... values) {
        return fetch(Users.USERS.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>create_at IN (values)</code>
     */
    public List<adapters.repository.jooq.tables.pojos.Users> fetchByCreateAt(Timestamp... values) {
        return fetch(Users.USERS.CREATE_AT, values);
    }

    /**
     * Fetch records that have <code>update_at IN (values)</code>
     */
    public List<adapters.repository.jooq.tables.pojos.Users> fetchByUpdateAt(Timestamp... values) {
        return fetch(Users.USERS.UPDATE_AT, values);
    }
}
