/*
 * This file is generated by jOOQ.
 */
package adapters.repository.jooq.tables.daos;


import adapters.repository.jooq.tables.UserSettings;
import adapters.repository.jooq.tables.records.UserSettingsRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSettingsDao extends DAOImpl<UserSettingsRecord, adapters.repository.jooq.tables.pojos.UserSettings, String> {

    /**
     * Create a new UserSettingsDao without any configuration
     */
    public UserSettingsDao() {
        super(UserSettings.USER_SETTINGS, adapters.repository.jooq.tables.pojos.UserSettings.class);
    }

    /**
     * Create a new UserSettingsDao with an attached configuration
     */
    public UserSettingsDao(Configuration configuration) {
        super(UserSettings.USER_SETTINGS, adapters.repository.jooq.tables.pojos.UserSettings.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(adapters.repository.jooq.tables.pojos.UserSettings object) {
        return object.getUsersId();
    }

    /**
     * Fetch records that have <code>users_id IN (values)</code>
     */
    public List<adapters.repository.jooq.tables.pojos.UserSettings> fetchByUsersId(String... values) {
        return fetch(UserSettings.USER_SETTINGS.USERS_ID, values);
    }

    /**
     * Fetch a unique record that has <code>users_id = value</code>
     */
    public adapters.repository.jooq.tables.pojos.UserSettings fetchOneByUsersId(String value) {
        return fetchOne(UserSettings.USER_SETTINGS.USERS_ID, value);
    }

    /**
     * Fetch records that have <code>init_savings IN (values)</code>
     */
    public List<adapters.repository.jooq.tables.pojos.UserSettings> fetchByInitSavings(Long... values) {
        return fetch(UserSettings.USER_SETTINGS.INIT_SAVINGS, values);
    }

    /**
     * Fetch records that have <code>update_at IN (values)</code>
     */
    public List<adapters.repository.jooq.tables.pojos.UserSettings> fetchByUpdateAt(Timestamp... values) {
        return fetch(UserSettings.USER_SETTINGS.UPDATE_AT, values);
    }
}
