/*
 * This file is generated by jOOQ.
 */
package adapters.repository.jooq;


import adapters.repository.jooq.tables.Balance;
import adapters.repository.jooq.tables.Tags;
import adapters.repository.jooq.tables.TagsMap;
import adapters.repository.jooq.tables.UserSettings;
import adapters.repository.jooq.tables.Users;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>remey</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index BALANCE_PKEY = Indexes0.BALANCE_PKEY;
    public static final Index TAGS_PKEY = Indexes0.TAGS_PKEY;
    public static final Index TAGS_MAP_PKEY = Indexes0.TAGS_MAP_PKEY;
    public static final Index USERS_PKEY = Indexes0.USERS_PKEY;
    public static final Index USER_SETTINGS_PKEY = Indexes0.USER_SETTINGS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index BALANCE_PKEY = Internal.createIndex("balance_pkey", Balance.BALANCE, new OrderField[] { Balance.BALANCE.ID }, true);
        public static Index TAGS_PKEY = Internal.createIndex("tags_pkey", Tags.TAGS, new OrderField[] { Tags.TAGS.ID }, true);
        public static Index TAGS_MAP_PKEY = Internal.createIndex("tags_map_pkey", TagsMap.TAGS_MAP, new OrderField[] { TagsMap.TAGS_MAP.BALANCE_ID, TagsMap.TAGS_MAP.TAGS_ID }, true);
        public static Index USERS_PKEY = Internal.createIndex("users_pkey", Users.USERS, new OrderField[] { Users.USERS.ID }, true);
        public static Index USER_SETTINGS_PKEY = Internal.createIndex("user_settings_pkey", UserSettings.USER_SETTINGS, new OrderField[] { UserSettings.USER_SETTINGS.USERS_ID }, true);
    }
}
