/*
 * This file is generated by jOOQ.
 */
package adapters.repository.jooq;


import adapters.repository.jooq.tables.Balance;
import adapters.repository.jooq.tables.Tags;
import adapters.repository.jooq.tables.TagsMap;
import adapters.repository.jooq.tables.UserSettings;
import adapters.repository.jooq.tables.Users;
import adapters.repository.jooq.tables.records.BalanceRecord;
import adapters.repository.jooq.tables.records.TagsMapRecord;
import adapters.repository.jooq.tables.records.TagsRecord;
import adapters.repository.jooq.tables.records.UserSettingsRecord;
import adapters.repository.jooq.tables.records.UsersRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>remey</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<BalanceRecord, Integer> IDENTITY_BALANCE = Identities0.IDENTITY_BALANCE;
    public static final Identity<TagsRecord, Integer> IDENTITY_TAGS = Identities0.IDENTITY_TAGS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BalanceRecord> BALANCE_PKEY = UniqueKeys0.BALANCE_PKEY;
    public static final UniqueKey<TagsRecord> TAGS_PKEY = UniqueKeys0.TAGS_PKEY;
    public static final UniqueKey<TagsMapRecord> TAGS_MAP_PKEY = UniqueKeys0.TAGS_MAP_PKEY;
    public static final UniqueKey<UsersRecord> USERS_PKEY = UniqueKeys0.USERS_PKEY;
    public static final UniqueKey<UserSettingsRecord> USER_SETTINGS_PKEY = UniqueKeys0.USER_SETTINGS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BalanceRecord, UsersRecord> BALANCE__BALANCE_USERS_ID_FKEY = ForeignKeys0.BALANCE__BALANCE_USERS_ID_FKEY;
    public static final ForeignKey<TagsRecord, UsersRecord> TAGS__TAGS_USERS_ID_FKEY = ForeignKeys0.TAGS__TAGS_USERS_ID_FKEY;
    public static final ForeignKey<TagsMapRecord, BalanceRecord> TAGS_MAP__TAGS_MAP_BALANCE_ID_FKEY = ForeignKeys0.TAGS_MAP__TAGS_MAP_BALANCE_ID_FKEY;
    public static final ForeignKey<TagsMapRecord, TagsRecord> TAGS_MAP__TAGS_MAP_TAGS_ID_FKEY = ForeignKeys0.TAGS_MAP__TAGS_MAP_TAGS_ID_FKEY;
    public static final ForeignKey<UserSettingsRecord, UsersRecord> USER_SETTINGS__USER_SETTINGS_USERS_ID_FKEY = ForeignKeys0.USER_SETTINGS__USER_SETTINGS_USERS_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<BalanceRecord, Integer> IDENTITY_BALANCE = Internal.createIdentity(Balance.BALANCE, Balance.BALANCE.ID);
        public static Identity<TagsRecord, Integer> IDENTITY_TAGS = Internal.createIdentity(Tags.TAGS, Tags.TAGS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<BalanceRecord> BALANCE_PKEY = Internal.createUniqueKey(Balance.BALANCE, "balance_pkey", Balance.BALANCE.ID);
        public static final UniqueKey<TagsRecord> TAGS_PKEY = Internal.createUniqueKey(Tags.TAGS, "tags_pkey", Tags.TAGS.ID);
        public static final UniqueKey<TagsMapRecord> TAGS_MAP_PKEY = Internal.createUniqueKey(TagsMap.TAGS_MAP, "tags_map_pkey", TagsMap.TAGS_MAP.BALANCE_ID, TagsMap.TAGS_MAP.TAGS_ID);
        public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, "users_pkey", Users.USERS.ID);
        public static final UniqueKey<UserSettingsRecord> USER_SETTINGS_PKEY = Internal.createUniqueKey(UserSettings.USER_SETTINGS, "user_settings_pkey", UserSettings.USER_SETTINGS.USERS_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<BalanceRecord, UsersRecord> BALANCE__BALANCE_USERS_ID_FKEY = Internal.createForeignKey(adapters.repository.jooq.Keys.USERS_PKEY, Balance.BALANCE, "balance__balance_users_id_fkey", Balance.BALANCE.USERS_ID);
        public static final ForeignKey<TagsRecord, UsersRecord> TAGS__TAGS_USERS_ID_FKEY = Internal.createForeignKey(adapters.repository.jooq.Keys.USERS_PKEY, Tags.TAGS, "tags__tags_users_id_fkey", Tags.TAGS.USERS_ID);
        public static final ForeignKey<TagsMapRecord, BalanceRecord> TAGS_MAP__TAGS_MAP_BALANCE_ID_FKEY = Internal.createForeignKey(adapters.repository.jooq.Keys.BALANCE_PKEY, TagsMap.TAGS_MAP, "tags_map__tags_map_balance_id_fkey", TagsMap.TAGS_MAP.BALANCE_ID);
        public static final ForeignKey<TagsMapRecord, TagsRecord> TAGS_MAP__TAGS_MAP_TAGS_ID_FKEY = Internal.createForeignKey(adapters.repository.jooq.Keys.TAGS_PKEY, TagsMap.TAGS_MAP, "tags_map__tags_map_tags_id_fkey", TagsMap.TAGS_MAP.TAGS_ID);
        public static final ForeignKey<UserSettingsRecord, UsersRecord> USER_SETTINGS__USER_SETTINGS_USERS_ID_FKEY = Internal.createForeignKey(adapters.repository.jooq.Keys.USERS_PKEY, UserSettings.USER_SETTINGS, "user_settings__user_settings_users_id_fkey", UserSettings.USER_SETTINGS.USERS_ID);
    }
}
