/*
 * This file is generated by jOOQ.
 */
package adapters.repository.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in remey
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>remey.balance_id_seq</code>
     */
    public static final Sequence<Integer> BALANCE_ID_SEQ = new SequenceImpl<Integer>("balance_id_seq", Remey.REMEY, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>remey.tags_id_seq</code>
     */
    public static final Sequence<Integer> TAGS_ID_SEQ = new SequenceImpl<Integer>("tags_id_seq", Remey.REMEY, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>remey.users_id_seq</code>
     */
    public static final Sequence<Integer> USERS_ID_SEQ = new SequenceImpl<Integer>("users_id_seq", Remey.REMEY, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
