/*
 * This file is generated by jOOQ.
*/
package remey.jooq;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import remey.jooq.tables.Shopping;
import remey.jooq.tables.Users;


/**
 * A class modelling indexes of tables of the <code>remey</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SHOPPING_PKEY = Indexes0.SHOPPING_PKEY;
    public static final Index USERS_PKEY = Indexes0.USERS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index SHOPPING_PKEY = Internal.createIndex("shopping_pkey", Shopping.SHOPPING, new OrderField[] { Shopping.SHOPPING.ID, Shopping.SHOPPING.USERS_ID }, true);
        public static Index USERS_PKEY = Internal.createIndex("users_pkey", Users.USERS, new OrderField[] { Users.USERS.ID }, true);
    }
}
