/*
 * This file is generated by jOOQ.
*/
package remey.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import remey.jooq.tables.Shopping;
import remey.jooq.tables.Users;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Remey extends SchemaImpl {

    private static final long serialVersionUID = 41150177;

    /**
     * The reference instance of <code>remey</code>
     */
    public static final Remey REMEY = new Remey();

    /**
     * The table <code>remey.shopping</code>.
     */
    public final Shopping SHOPPING = remey.jooq.tables.Shopping.SHOPPING;

    /**
     * The table <code>remey.users</code>.
     */
    public final Users USERS = remey.jooq.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private Remey() {
        super("remey", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.SHOPPING_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Shopping.SHOPPING,
            Users.USERS);
    }
}
