/*
 * This file is generated by jOOQ.
*/
package remey.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in remey
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>remey.shopping_id_seq</code>
     */
    public static final Sequence<Integer> SHOPPING_ID_SEQ = new SequenceImpl<Integer>("shopping_id_seq", Remey.REMEY, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
