/*
 * This file is generated by jOOQ.
*/
package remey.jooq;


import javax.annotation.Generated;

import remey.jooq.tables.Shopping;
import remey.jooq.tables.Users;


/**
 * Convenience access to all tables in remey
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>remey.shopping</code>.
     */
    public static final Shopping SHOPPING = remey.jooq.tables.Shopping.SHOPPING;

    /**
     * The table <code>remey.users</code>.
     */
    public static final Users USERS = remey.jooq.tables.Users.USERS;
}
